server:
  port: 8000
spring:
  application:
    name: msa-gateway
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/first-service/**
        - id: second-service
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/second-service/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka