server:
  port: 8888
spring:
  config:
    import:
      - private.yml
  application:
    name: msa-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:writer0713/msa-practice-config.git
          ignoreLocalSshSettings: true
          private-key: ${git.private-key}
  docker:
    compose:
      enabled: true
      file: docker/rabbitmq.yaml
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
